@IsTest
public class Quote_AutoQuoteControllerTest {
    //public boolean getAutoQuoteViewEnabled;
    public boolean AutoClose;
    static testMethod void myUnitTest()
    {
        PageReference pageRef = Page.Quote_AutoQuote;
        Test.setCurrentPage(pageRef);
        
       // Quote_AutoQuoteController qac = new Quote_AutoQuoteController();
        //qa.setAutoQuoteViewEnabled(true);
        //qa.LoadInitialState();
       // qa.TriggerAutoQuote();
       // qac.AutoClose=true;
        
    }
}