/*************************************************************************\
    @ Author        : Absyz Software Consulting Pvt. Ltd.
    @ Date          : 09-June-2016
    @ Test File     : 
    @ Description   : To remove hard coding in classes we can refer the string variables in this class
    @ Audit Trial   : 
    @ Last Modified Date : 09-June-2016
  
****************************************************************************/ 

public class StringVariablesHelper {

    public static string Welcome = 'You are receiving this e-mail because you have been added to the referenced Service Case by a colleague or the case has been updated.';
    public static string CaseNumber = 'Case Number: ';
    public static string problemType = 'Problem Type: ';
    public static string subject ='Case Subject: ';
    public static string priority ='Priority: ';
    public static string Description ='Case Description: ';
    public static string comment = 'Case Comments: ';
    public static string link ='Case Link: ';
    public static string Thanks ='Thank You!';
    public static string CaseName ='Case # ';
    public static string updated = 'has been updated. ';
    public static string Order = 'Order # ' ;
}