@isTest
public class testaccount_normalizefields {
    /*static testmethod void normalize(){
        list<Zip_Codes_Master__c> tmList = TestDataUtility.getTerritoryMaster();
        insert tmList;
         Account a = new Account();
        a.Name='My Test Account1';
        a.BillingCity='new va'; 
            a.BillingCountry='United States'; 
            a.BillingPostalCode='12345'; 
            a.BillingState='New York'; 
            a.BillingStreet='xyz street';
            a.ShippingCity=' '; 
            a.City__c = '';
            a.ShippingCountry='United States'; 
            a.ShippingPostalCode='12345'; 
            a.ShippingState=' '; 
            a.ShippingStreet='xy'; 
            a.Phone='5432167'; 
            a.Fax='444-5555';
        
        test.startTest();
             insert a;
        test.stopTest();
    }*/
}