@isTest
Private class TestSinglepageleadConvert{
 /*public static List<Account> olstTestAccount;
  public static List<Lead> olstTestLead;
  public static List<Project__c> olstTestProject;
  public static List<Contact> olstContact;
  public static List<Opportunity> olstOpportunity;
  public static list<OpportunityContactRole> olstTestOppConRole;
 Static testMethod void Convert(){
 olstTestAccount=TestDataUtility.createAccountTestData();
 insert olstTestAccount;
 olstTestLead=TestDataUtility.createLeadTestData();
 insert olstTestLead;
 olstContact=TestDataUtility.createConTestData();
  olstContact[0].Account=olstTestAccount[0];
 insert olstContact;
 olstOpportunity=TestDataUtility.createOppTestData();
 insert olstOpportunity;

 
 olstTestOppConRole=TestDataUtility.createOppConRoleTestData(olstOpportunity ,olstContact);
  insert olstTestOppConRole;
 olstTestProject=TestDataUtility.createProjectTestData();
  olstTestProject[0].Project_State__c='California';
 olstTestProject[0].Project_City__c='San Jose';
 olstTestProject[0].Project_Country__c='United States';
 olstTestProject[0].Project_Street_Address__c='Blossom Hill Road';
 insert olstTestProject;
 
    
    SinglePageLeadConvertController Splc= new SinglePageLeadConvertController();
    Splc.getItems();
     Splc.getrecType();
     Splc.getAppItems();
     Splc.getduplicateopps();
     Splc.validateFields();
     Splc.continueWithProject();
     Splc.CreateObjects();
     Splc.updateAddressNew(); 
     Splc.onProjectCheck();
     Splc.getaccounttype();
 }*/
    }