public with sharing class UnitTests3 {


	@isTest(SeeAllData=false)
    static  void RunTests () {
         //utility, test the zip codes
		Utility.getUserForTerritory('USA', '31999'); 
		Utility.getUserForTerritory('USA', '96199');
		Utility.getUserForTerritory('USA', '89899');
		Utility.getUserForTerritory('USA', '07699');
		Utility.getUserForTerritory('USA', '07999');
		Utility.getUserForTerritory('USA', '12799');
		Utility.getUserForTerritory('USA', '02799');
		Utility.getUserForTerritory('USA', '02999');
		Utility.getUserForTerritory('USA', '03899');
		Utility.getUserForTerritory('USA', '04999');
		Utility.getUserForTerritory('USA', '05999');
		Utility.getUserForTerritory('USA', '06999');
		Utility.getUserForTerritory('USA', '61999');
		Utility.getUserForTerritory('USA', '62399');
		Utility.getUserForTerritory('USA', '62799');
		Utility.getUserForTerritory('USA', '53999');
		Utility.getUserForTerritory('USA', '54599');
		Utility.getUserForTerritory('USA', '43299');
		Utility.getUserForTerritory('USA', '43999');
		Utility.getUserForTerritory('USA', '45799');
		Utility.getUserForTerritory('USA', '45799');
		Utility.getUserForTerritory('USA', '16899');
		Utility.getUserForTerritory('USA', '17299');
		Utility.getUserForTerritory('USA', '19699');
		Utility.getUserForTerritory('USA', '17199');
		Utility.getUserForTerritory('USA', '08999');
		Utility.getUserForTerritory('USA', '07799');
		Utility.getUserForTerritory('USA', '78999');
		Utility.getUserForTerritory('USA', '79999');
		Utility.getUserForTerritory('USA', '76899');
		Utility.getUserForTerritory('USA', '74999');
		Utility.getUserForTerritory('USA', '79699');
		Utility.getUserForTerritory('USA', '19999');
		Utility.getUserForTerritory('USA', '21999');
		Utility.getUserForTerritory('USA', '24699');
		Utility.getUserForTerritory('USA', '26899');
		Utility.getUserForTerritory('USA', '48999');
		Utility.getUserForTerritory('USA', '49199');
		Utility.getUserForTerritory('USA', '49299');
		Utility.getUserForTerritory('USA', '49599');
		Utility.getUserForTerritory('USA', '48999');
		Utility.getUserForTerritory('USA',  '83199');
		Utility.getUserForTerritory('USA',  '59399');
		Utility.getUserForTerritory('USA',  '88999');
		Utility.getUserForTerritory('USA',  '59599');
		Utility.getUserForTerritory('USA',  '34199');
		Utility.getUserForTerritory('USA',  '34999');
		Utility.getUserForTerritory('USA',  '33999');
		Utility.getUserForTerritory('USA', '32971');
		Utility.getUserForTerritory('USA', '33499');
		Utility.getUserForTerritory('USA', '56999');
		Utility.getUserForTerritory('USA', '54099');
		Utility.getUserForTerritory('USA', '54899');
		Utility.getUserForTerritory('USA', '58999');
		Utility.getUserForTerritory('USA', '57999');
		Utility.getUserForTerritory('USA', '44799');
		Utility.getUserForTerritory('USA', '44999');
		Utility.getUserForTerritory('USA', '43699');
		Utility.getUserForTerritory('USA', '45899');
		Utility.getUserForTerritory('USA', '44599');
		Utility.getUserForTerritory('USA', '83999');
		Utility.getUserForTerritory('USA', '96999');
		Utility.getUserForTerritory('USA', '59499');
		Utility.getUserForTerritory('USA', '59999');
		Utility.getUserForTerritory('USA', '97999');
		Utility.getUserForTerritory('USA', '99499');
		Utility.getUserForTerritory('USA', '99999');
		Utility.getUserForTerritory('USA', '29999');
		Utility.getUserForTerritory('USA', '34100');
		Utility.getUserForTerritory('USA', '34399');
		Utility.getUserForTerritory('USA', '67999');
		Utility.getUserForTerritory('USA', '93599');
		Utility.getUserForTerritory('USA', '11999');
		Utility.getUserForTerritory('USA', '32299');
		Utility.getUserForTerritory('USA', '32959');
		Utility.getUserForTerritory('USA', '34799');
		Utility.getUserForTerritory('USA', '32959');
		Utility.getUserForTerritory('USA', '32999');
		Utility.getUserForTerritory('USA', '54599');
		Utility.getUserForTerritory('USA', '45799');
		Utility.getUserForTerritory('USA', '48999');
		Utility.getUserForTerritory('USA', '34100');
		Utility.getUserForTerritory('USA', '32959');
		 
		Utility.getUserForTerritory('USA', '12001');
		Utility.getUserForTerritory('USA', '12801');
		Utility.getUserForTerritory('USA', '27001');
		Utility.getUserForTerritory('USA', '32301');
		Utility.getUserForTerritory('USA', '32401');
		Utility.getUserForTerritory('USA', '32601');
		Utility.getUserForTerritory('USA', '32901');
		Utility.getUserForTerritory('USA', '33501');
		Utility.getUserForTerritory('USA', '34201');
		Utility.getUserForTerritory('USA', '32901');
		Utility.getUserForTerritory('USA', '62301');
		Utility.getUserForTerritory('USA', '62501');
		Utility.getUserForTerritory('USA', '70201');
		Utility.getUserForTerritory('USA', '70301');
		Utility.getUserForTerritory('USA', '70901');
		Utility.getUserForTerritory('USA', '71001');
		Utility.getUserForTerritory('USA', '71201');
		Utility.getUserForTerritory('USA', '71301');
		Utility.getUserForTerritory('USA', '71501');
		Utility.getUserForTerritory('USA', '71601');
		Utility.getUserForTerritory('USA', '77001');
		Utility.getUserForTerritory('USA', '83201');
		Utility.getUserForTerritory('USA', '62301');
		Utility.getUserForTerritory('USA', '62501');
		Utility.getUserForTerritory('USA', '70201');
		Utility.getUserForTerritory('USA', '70301');
		Utility.getUserForTerritory('USA', '70901');
		Utility.getUserForTerritory('USA', '71001');
		Utility.getUserForTerritory('USA', '71201');
		Utility.getUserForTerritory('USA', '71301');
		Utility.getUserForTerritory('USA', '71501');
		Utility.getUserForTerritory('USA', '71601');
		Utility.getUserForTerritory('USA', '77001');
		Utility.getUserForTerritory('USA', '84001');
		Utility.getUserForTerritory('USA', '85001');
		Utility.getUserForTerritory('USA', '89001');
		Utility.getUserForTerritory('USA', '96701');
		Utility.getUserForTerritory('USA', '00601');
		Utility.getUserForTerritory('USA', '666');
        Utility.getUserForTerritory('canada', 'v4v');
        Utility.getUserForTerritory('canada', 'v99');
        Utility.getUserForTerritory('canada', '4v');
        Utility.getUserForTerritory('canada', 'tv');
        Utility.getUserForTerritory('canada', 'jv');
        Utility.getUserForTerritory('canada', 'lv');
        Utility.getUserForTerritory('canada', 'xv');
            
        //utiliy get user special cases
        Utility.getUserForTerritory('USA', '1');

        Utility.HostName();
        
        Utility.StateOptions();
	    Utility.CountryOptions();
        
        // ...
	    try
	    {
		    NanaQuoteGateway nqg = new NanaQuoteGateway();
		     NanaQuoteGateway.ArrayOfString GetAllUserNamesResult= new NanaQuoteGateway.ArrayOfString();
		    NanaQuoteGateway.GetAllUserNamesResponse_element e = new NanaQuoteGateway.GetAllUserNamesResponse_element();
		    NanaQuoteGateway.GetUserXmlByUsernameResponse_element f = new NanaQuoteGateway.GetUserXmlByUsernameResponse_element();
		    NanaQuoteGateway.GetSolidworksSingleResponse_element g = new NanaQuoteGateway.GetSolidworksSingleResponse_element();
		    NanaQuoteGateway.Get3DFormatsResponse_element h = new NanaQuoteGateway.Get3DFormatsResponse_element();
		    NanaQuoteGateway.GetSolidworks_element i = new NanaQuoteGateway.GetSolidworks_element();
		    NanaQuoteGateway.GetAllUsersXML_element j = new NanaQuoteGateway.GetAllUsersXML_element();
		    NanaQuoteGateway.GetQuoteByID2Response_element k = new NanaQuoteGateway.GetQuoteByID2Response_element();
		    NanaQuoteGateway.AvailableProjectTypesResponse_element r = new NanaQuoteGateway.AvailableProjectTypesResponse_element();
		    NanaQuoteGateway.wsoQuote m = new NanaQuoteGateway.wsoQuote();
		    NanaQuoteGateway.wsoLead s = new NanaQuoteGateway.wsoLead();
		    
		    NanaQuoteGateway.ArrayOfWsoQuoteDetail n2 = new NanaQuoteGateway.ArrayOfWsoQuoteDetail();
		    NanaQuoteGateway.QuoteRequestInput_element o = new NanaQuoteGateway.QuoteRequestInput_element();
		    NanaQuoteGateway.UpdateLead_element p = new NanaQuoteGateway.UpdateLead_element();
		    NanaQuoteGateway.wsoProject t = new NanaQuoteGateway.wsoProject();
		    NanaQuoteGateway.GetQuoteByID2_element u = new NanaQuoteGateway.GetQuoteByID2_element();
		    NanaQuoteGateway.GetUserXmlByUsernameResult_element v = new NanaQuoteGateway.GetUserXmlByUsernameResult_element();
		    NanaQuoteGateway.GetWebQuoteByID_element w = new NanaQuoteGateway.GetWebQuoteByID_element();
		    NanaQuoteGateway.wsoChoice x= new NanaQuoteGateway.wsoChoice();
		    NanaQuoteGateway.GetQuoteDetailByIDResponse_element y= new NanaQuoteGateway.GetQuoteDetailByIDResponse_element();
		    NanaQuoteGateway.HandleQuoteRequestResult_element z= new NanaQuoteGateway.HandleQuoteRequestResult_element();
		    NanaQuoteGateway.GetSolidworksLinkResponse_element aa= new NanaQuoteGateway.GetSolidworksLinkResponse_element();
		    NanaQuoteGateway.GetQuoteByIDResponse_element ab= new NanaQuoteGateway.GetQuoteByIDResponse_element();
		    NanaQuoteGateway.HandleQuoteRequestResponse_element ac = new NanaQuoteGateway.HandleQuoteRequestResponse_element();
		    NanaQuoteGateway.ArrayOfString ad = new NanaQuoteGateway.ArrayOfString();
		    NanaQuoteGateway.UpdateUser_element ae = new NanaQuoteGateway.UpdateUser_element();
		    NanaQuoteGateway.EQuoteMetric_element af = new NanaQuoteGateway.EQuoteMetric_element();
		    NanaQuoteGateway.GetQuoteByID2Result_element ag = new NanaQuoteGateway.GetQuoteByID2Result_element();
		    NanaQuoteGateway.HandleQuoteRequest_element az = new NanaQuoteGateway.HandleQuoteRequest_element();
		    NanaQuoteGateway.ArrayOfWsoQuote ay = new NanaQuoteGateway.ArrayOfWsoQuote();
		    NanaQuoteGateway.EQuoteMetricResult_element ax = new NanaQuoteGateway.EQuoteMetricResult_element();
		    NanaQuoteGateway.HandleQuoteRequest2_element aw = new NanaQuoteGateway.HandleQuoteRequest2_element();
		    NanaQuoteGateway.ArrayOfWsoLead av = new NanaQuoteGateway.ArrayOfWsoLead();
		    NanaQuoteGateway.GetProjectsByLeadIDResponse_element ah2 = new NanaQuoteGateway.GetProjectsByLeadIDResponse_element();
		    NanaQuoteGateway.GetQuoteDetailsByIDResponse_element ai = new NanaQuoteGateway.GetQuoteDetailsByIDResponse_element();
		    NanaQuoteGateway.CreateQuote_element aj = new NanaQuoteGateway.CreateQuote_element();
		    NanaQuoteGateway.AuthenticateUserResponse_element ak = new NanaQuoteGateway.AuthenticateUserResponse_element();
		    NanaQuoteGateway.AvailableProjectTypes_element al2 = new NanaQuoteGateway.AvailableProjectTypes_element();
		    NanaQuoteGateway.wsoAddress am = new NanaQuoteGateway.wsoAddress();
		    NanaQuoteGateway.GetQuoteDetailsByID_element an = new NanaQuoteGateway.GetQuoteDetailsByID_element();
		    NanaQuoteGateway.GetAllUsersXMLResponse_element ao = new NanaQuoteGateway.GetAllUsersXMLResponse_element();
		    NanaQuoteGateway.AuthenticateUserResult_element ap2 = new NanaQuoteGateway.AuthenticateUserResult_element();
		    NanaQuoteGateway.GetWebQuoteByIDResult_element aq = new NanaQuoteGateway.GetWebQuoteByIDResult_element();
		    NanaQuoteGateway.GetQuoteDetailByIDResult_element aaa = new NanaQuoteGateway.GetQuoteDetailByIDResult_element();
		    NanaQuoteGateway.ArrayOfWsoChoice ar = new NanaQuoteGateway.ArrayOfWsoChoice();
		    NanaQuoteGateway.AssociateLead_element at = new NanaQuoteGateway.AssociateLead_element();
		    NanaQuoteGateway.GetQuoteByID_element au = new NanaQuoteGateway.GetQuoteByID_element();
		    NanaQuoteGateway.GetUserXmlByUsername_element ba = new NanaQuoteGateway.GetUserXmlByUsername_element();
		    NanaQuoteGateway.GetQuoteDetailByID_element bb = new NanaQuoteGateway.GetQuoteDetailByID_element();
			NanaQuoteGateway.QuoteGatewaySoap qgs = new NanaQuoteGateway.QuoteGatewaySoap();
		    qgs.GetUserXmlByUsername('');
		    qgs.GetQuoteByID(0);
		    qgs.HandleQuoteRequest(o);
		    qgs.GetSolidworks(0);
		    qgs.UpdateLead('',null);
		    qgs.CreateQuote('');
		    qgs.UpdateUser('',null);
		    qgs.GetWebQuoteByID(0);
		    qgs.GetSolidworksLink('');
		    qgs.AuthenticateUser('','','');
		    qgs.AssociateLead(0, 0, 0, '');
		    qgs.AvailableProjectTypes();
		    qgs.GetAllUserNames();
		    qgs.Get3DFormats();
		    qgs.GetQuotesByProjectID(0);
		    qgs.GetQuoteDetailsByID(0);
		    qgs.GetAllUsersXML();
		    qgs.GetQuoteByID2(0);
		    qgs.GetQuoteDetailByID(0);
		    String hqr = qgs.HandleQuoteRequest2('a');
		    qgs.GetProjectsByLeadID(0);
		    qgs.GetSolidWorksSingle(0,false);
		    qgs.EQuoteMetric('',0,0); 
		    NanaQuoteGateway.GetQuotesByProjectID_element bc = new NanaQuoteGateway.GetQuotesByProjectID_element();
		    NanaQuoteGateway.GetAllUserNames_element bd = new NanaQuoteGateway.GetAllUserNames_element();
		    NanaQuoteGateway.ArrayOfWsoProject be = new NanaQuoteGateway.ArrayOfWsoProject();
		    NanaQuoteGateway.wsoProjectType bf = new NanaQuoteGateway.wsoProjectType();
		    NanaQuoteGateway.HandleQuoteRequest2Response_element bg = new NanaQuoteGateway.HandleQuoteRequest2Response_element();
		    NanaQuoteGateway.GetSolidworksSingle_element bh = new NanaQuoteGateway.GetSolidworksSingle_element();
		    NanaQuoteGateway.GetAllUsersXMLResult_element bi = new NanaQuoteGateway.GetAllUsersXMLResult_element();
		    NanaQuoteGateway.Get3DFormats_element bj = new NanaQuoteGateway.Get3DFormats_element();
		    NanaQuoteGateway.wsoQuoteDetail bk = new NanaQuoteGateway.wsoQuoteDetail();
		    NanaQuoteGateway.ArrayOfInt bl = new NanaQuoteGateway.ArrayOfInt();
		    NanaQuoteGateway.XML_element bm = new NanaQuoteGateway.XML_element();
		    NanaQuoteGateway.settings_element bn = new NanaQuoteGateway.settings_element();
		    NanaQuoteGateway.GetSolidworksLink_element bo = new NanaQuoteGateway.GetSolidworksLink_element();
		    NanaQuoteGateway.ArrayOfWsoProjectType bp = new NanaQuoteGateway.ArrayOfWsoProjectType();
		    NanaQuoteGateway.GetWebQuoteByIDResponse_element bq = new NanaQuoteGateway.GetWebQuoteByIDResponse_element();
		    NanaQuoteGateway.GetProjectsByLeadID_element br = new NanaQuoteGateway.GetProjectsByLeadID_element();
		    NanaQuoteGateway.GetSolidworksResponse_element bs = new NanaQuoteGateway.GetSolidworksResponse_element();
		    NanaQuoteGateway.AssociateLeadResponse_element bt = new NanaQuoteGateway.AssociateLeadResponse_element();
		    NanaQuoteGateway.EQuoteMetricResponse_element bu = new NanaQuoteGateway.EQuoteMetricResponse_element();
		    NanaQuoteGateway.ArrayOfWsoRep bv = new NanaQuoteGateway.ArrayOfWsoRep();
		    NanaQuoteGateway.GetQuotesByProjectIDResponse_element bw = new NanaQuoteGateway.GetQuotesByProjectIDResponse_element();
		    NanaQuoteGateway.wsoRep bx = new NanaQuoteGateway.wsoRep();
		    NanaQuoteGateway.AuthenticateUser_element bz = new NanaQuoteGateway.AuthenticateUser_element();
		    NanaQuoteGateway.UpdateUserResponse_element ca = new NanaQuoteGateway.UpdateUserResponse_element();
		    NanaQuoteGateway.UpdateLeadResponse_element cb = new NanaQuoteGateway.UpdateLeadResponse_element();
		    NanaQuoteGateway.CreateQuoteResponse_element cc = new NanaQuoteGateway.CreateQuoteResponse_element();
	    }
	    catch (Exception ex)
	    {
	    } 
	            
            	
         try
         {
         	XMLDom dom= new XMLDom();
         	dom = new XMLDom('');
         	dom.dumpAll();
         	dom.getElementByTagName('');
         	dom.getElementsByTagName('');
         	dom.ownerDocument();
         	dom.parseFromString('');
         	dom.toXmlString();
         	dom.dumpList(null);
         	
         
         }
         catch (Exception ex){}
         
            	
    }
}