@istest
public class wrapperObjectShopifyTest {
    static testMethod void shopifyWrapperMethod() {
        ShopifyBatch.shopifywrapper shopwpr = new ShopifyBatch.shopifywrapper();
        shopwpr.Order.email = 'test@nanawall.com';
        shopwpr.Order.total_price = 100;
        shopwpr.Order.subtotal_price = 100;
        shopwpr.Order.total_weight = 100;
        shopwpr.Order.total_tax = 100;
       // wrapperObjectShopify wrapper = new wrapperObjectShopify();
       // wrapper.default_address;
        
       // wrapperObjectShopify.order tmpObj = new wrapperObjectShopify.order();
    //wrapperObjectShopify wrapper = new wrapperObjectShopify();
    //string email = 'test@nanawall.com';
   // wrapper.default_address orderObj = new wrapper.default_address();
      //  orderObj.first_name = ' ';
       
        //orderObj.id;
       // tmpObj.email = 'test@nanawall.com';
        /*&orderObj.created_at = '2017-30-05';
        orderObj.note = ' ';
        orderObj.total_price = 100;
        orderObj.subtotal_price = 100;
        orderObj.total_weight = 100;
        orderObj.total_tax = 100;
        orderObj.fulfillment_status = '';
        orderObj.cancelled_at = '2017-30-05';
        orderObj.financial_status = '';
        orderObj.total_discounts = '';
        orderObj.total_line_items_price = '';*/
        //orderObj List < line_items > line_items;
        //orderObj billing_address billing_address;
        //orderObj shipping_address shipping_address;
        //orderObj customer customer;
        //orderObj list < note_attributes > note_attributes;
        //orderObj string cancel_reason;
        //orderObj List < fulfillments > fulfillments;
       // orderObj.name = '';
    }}