public class ZillowConfig {

    public static final String ZWSID = 'X1-ZWz1c32g1dm22z_aqadi' ; // paste your own token here
    public static final String PROPERTY_SEARCH_URL='http://www.zillow.com/webservice/GetSearchResults.htm?zws-id=' ;
    public static final String DEMOGRAPHICS_URL='http://www.zillow.com/webservice/GetDemographics.htm?zws-id=' ; 
    
    // other URLs for other services
    
    
    
}